<?php

$crud = static function (string $group, string $resource): array {
    return [
        "{$resource}.view" => ['group' => $group, 'label' => 'View '.$resource],
        "{$resource}.create" => ['group' => $group, 'label' => 'Create '.$resource],
        "{$resource}.update" => ['group' => $group, 'label' => 'Edit '.$resource],
        "{$resource}.delete" => ['group' => $group, 'label' => 'Delete '.$resource],
    ];
};

return [
    'permissions' => array_merge(
        [
            'dashboard.view' => ['group' => 'Dashboard', 'label' => 'View dashboard'],
        ],
        $crud('Content', 'pages'),
        $crud('Content', 'categories'),
        $crud('Content', 'posts'),
        $crud('Content', 'projects'),
        $crud('Content', 'faqs'),
        $crud('Content', 'impact'),
        $crud('Content', 'press'),
        $crud('Content', 'notices'),
        $crud('Media', 'gallery'),
        $crud('Media', 'graphics'),
        $crud('Media', 'videos'),
        $crud('Media', 'media'),
        $crud('Operations', 'prices'),
        [
            'registry.view' => ['group' => 'Operations', 'label' => 'View license registry'],
            'registry.create' => ['group' => 'Operations', 'label' => 'Create license registry entries'],
            'registry.update' => ['group' => 'Operations', 'label' => 'Edit license registry entries'],
            'registry.delete' => ['group' => 'Operations', 'label' => 'Delete license registry entries'],
            'registry.import' => ['group' => 'Operations', 'label' => 'Import license registry entries'],
        ],
        $crud('People', 'people'),
        $crud('Repository', 'documents'),
        $crud('System', 'users'),
        $crud('System', 'roles'),
        [
            'activity.view' => ['group' => 'System', 'label' => 'View activity log'],
            'trash.view' => ['group' => 'System', 'label' => 'View trash'],
            'trash.restore' => ['group' => 'System', 'label' => 'Restore deleted records'],
            'trash.delete' => ['group' => 'System', 'label' => 'Permanently delete records'],
            'settings.view' => ['group' => 'System', 'label' => 'View settings'],
            'settings.update' => ['group' => 'System', 'label' => 'Edit settings'],
        ],
    ),

    'roles' => [
        'super-admin' => [
            'name' => 'Super Admin',
            'description' => 'Full access to every CMS area and system setting.',
            'permissions' => ['*'],
        ],
        'content-manager' => [
            'name' => 'Content Manager',
            'description' => 'Can manage publishing workflows, media, documents, and public website content.',
            'permissions' => [
                'dashboard.view',
                'pages.view',
                'pages.create',
                'pages.update',
                'pages.delete',
                'categories.view',
                'categories.create',
                'categories.update',
                'categories.delete',
                'posts.view',
                'posts.create',
                'posts.update',
                'posts.delete',
                'projects.view',
                'projects.create',
                'projects.update',
                'projects.delete',
                'faqs.view',
                'faqs.create',
                'faqs.update',
                'faqs.delete',
                'impact.view',
                'impact.create',
                'impact.update',
                'impact.delete',
                'press.view',
                'press.create',
                'press.update',
                'press.delete',
                'notices.view',
                'notices.create',
                'notices.update',
                'notices.delete',
                'gallery.view',
                'gallery.create',
                'gallery.update',
                'gallery.delete',
                'graphics.view',
                'graphics.create',
                'graphics.update',
                'graphics.delete',
                'videos.view',
                'videos.create',
                'videos.update',
                'videos.delete',
                'media.view',
                'media.create',
                'media.update',
                'media.delete',
                'people.view',
                'people.create',
                'people.update',
                'people.delete',
                'documents.view',
                'documents.create',
                'documents.update',
                'documents.delete',
                'activity.view',
            ],
        ],
        'publisher' => [
            'name' => 'Publisher',
            'description' => 'Focused access for posts, pages, press releases, notices, media, gallery, graphics, and videos.',
            'permissions' => [
                'dashboard.view',
                'pages.view',
                'pages.create',
                'pages.update',
                'posts.view',
                'posts.create',
                'posts.update',
                'projects.view',
                'projects.create',
                'projects.update',
                'faqs.view',
                'faqs.create',
                'faqs.update',
                'impact.view',
                'impact.create',
                'impact.update',
                'press.view',
                'press.create',
                'press.update',
                'notices.view',
                'notices.create',
                'notices.update',
                'gallery.view',
                'gallery.create',
                'gallery.update',
                'graphics.view',
                'graphics.create',
                'graphics.update',
                'videos.view',
                'videos.create',
                'videos.update',
                'media.view',
                'media.create',
                'media.update',
            ],
        ],
        'auditor' => [
            'name' => 'Auditor',
            'description' => 'Read operational activity and review CMS dashboard metrics.',
            'permissions' => [
                'dashboard.view',
                'activity.view',
            ],
        ],
    ],
];
