<?php

return [
    'projects' => [
        'gwyesco' => [
            'name' => 'GWYESCO',
            'full_name' => 'Ghana Women & Youth Employment and Social Cohesion Programme',
            'status' => 'New · Launched 2026',
            'timeline' => '2026 - 2028',
            'funder' => 'African Development Bank (AfDB)',
            'fund_amount' => 'US$71.25M grant',
            'zone' => 'Savannah Belt',
            'regions' => ['Northern', 'Upper East', 'Upper West', 'North East', 'Savannah', 'Nationwide'],
            'image' => '/images/gwyesco-launch.jpg',
            'summary' => "Ghana's first AfDB results-based financing operation: training 30,000+ women and young people in STEM, digital and creative skills, expanding MSME finance access, and rebuilding social cohesion in northern Ghana.",
            'objectives' => [
                'Equip 30,000+ women and young people with STEM, digital and TVET skills.',
                'Expand access to MSME finance for women- and youth-led enterprises.',
                'Strengthen social cohesion and resilience in conflict-affected communities in northern Ghana.',
            ],
            'outcomes' => [
                "Ghana's first AfDB results-based financing operation, disbursed against verified results.",
                'Ministry of Finance is the executing agency; SIF is the implementing agency.',
                'Programme runs 2026-2028 across STEM, digital, TVET training and enterprise finance tracks.',
            ],
            'beneficiaries' => '30,000+ women and young people, with priority given to communities in northern Ghana.',
            'seo_title' => 'GWYESCO Project | Women, Youth and Social Cohesion',
            'seo_description' => 'Learn about GWYESCO, SIF Ghana’s programme supporting women and young people with skills, MSME finance access and social cohesion opportunities.',
        ],
        'psdpep' => [
            'name' => 'PSDPEP',
            'full_name' => 'Post-COVID-19 Skills Development and Productivity Enhancement Project',
            'status' => 'Ongoing · 2023 - 2027',
            'timeline' => '2023 - 2027',
            'funder' => 'AfDB and Government of Ghana',
            'fund_amount' => 'US$31.3M total',
            'zone' => 'Eastern Seaboard',
            'regions' => ['Greater Accra', 'Northern', 'Western', 'Nationwide'],
            'image' => 'https://sifinghana.org/backend/images/uploads/PSDPEP%20scholar.jpg%20web.jpg1743597962.jpg',
            'summary' => 'Rehabilitating health and education infrastructure and putting low-interest microcredit into the hands of women- and youth-led MSMEs, in partnership with the Ghana News Agency, MASLOC and the University of Ghana.',
            'objectives' => [
                'Rehabilitate Ghana News Agency regional offices in Accra, Tema, Tamale and Takoradi.',
                'Deliver a US$4M MSME microcredit facility for women- and youth-led enterprises.',
                'Strengthen productivity and post-pandemic recovery through institutional partnerships.',
            ],
            'outcomes' => [
                'GNA office rehabilitation under way in Accra, Tema, Tamale and Takoradi.',
                'US$4M microcredit facility established for MSME access to finance.',
                'Delivered in partnership with the Ghana News Agency, MASLOC and the University of Ghana.',
            ],
            'beneficiaries' => 'Women- and youth-led MSMEs, GNA staff and surrounding communities across four regional hubs.',
            'seo_title' => 'PSDPEP Project | Skills Development and Productivity',
            'seo_description' => 'Explore PSDPEP, SIF Ghana’s post-COVID skills, productivity, microcredit, health and education infrastructure support programme.',
        ],
        'irdp2' => [
            'name' => 'IRDP II',
            'full_name' => 'Integrated Rural Development Project, Phase II',
            'status' => 'Ongoing',
            'timeline' => 'Ongoing',
            'funder' => 'OPEC Fund for International Development (OFID)',
            'fund_amount' => 'OFID-financed',
            'zone' => 'Forest and Transition',
            'regions' => ['Ashanti', 'Nationwide rural districts'],
            'image' => 'https://sifinghana.org/backend/images/uploads/afigya%20kwabre%20irdp%202.jpg1742825153.jpg',
            'summary' => 'The second phase of integrated rural development extends socio-economic infrastructure and livelihood support to underserved rural districts nationwide.',
            'objectives' => [
                'Extend socio-economic infrastructure to underserved rural districts.',
                'Build on the foundation and lessons of IRDP I.',
                'Strengthen livelihoods alongside infrastructure delivery.',
            ],
            'outcomes' => [
                'Active infrastructure works recorded in Afigya Kwabre, Ashanti Region.',
                'Continued rollout nationwide, subject to OFID fund-release schedules.',
            ],
            'beneficiaries' => 'Rural communities across multiple districts, including Afigya Kwabre in the Ashanti Region.',
            'seo_title' => 'IRDP II Project | Rural Infrastructure Delivery',
            'seo_description' => 'View details of IRDP II, SIF Ghana’s integrated rural development programme supporting socio-economic infrastructure in underserved districts.',
        ],
        'irdp1' => [
            'name' => 'IRDP I',
            'full_name' => 'Integrated Rural Development Project, Phase I',
            'status' => 'Completed',
            'timeline' => 'Completed',
            'funder' => 'Development Partners and Government of Ghana',
            'fund_amount' => '-',
            'zone' => 'Forest and Transition',
            'regions' => ['Nationwide - 21 districts'],
            'image' => 'https://sifinghana.org/backend/images/uploads/IRDP1.png1741004874.png',
            'summary' => 'Rural development delivered across 21 districts, creating more than 2,000 employment opportunities and laying the operating model for IRDP II.',
            'objectives' => [
                'Deliver socio-economic infrastructure across 21 rural districts.',
                'Generate sustainable employment opportunities for rural communities.',
                'Establish the integrated rural development model later scaled in IRDP II.',
            ],
            'outcomes' => [
                'More than 2,000 employment opportunities created across 21 districts.',
                'Programme completed and succeeded by IRDP II.',
            ],
            'beneficiaries' => 'Rural communities across 21 districts nationwide.',
            'seo_title' => 'IRDP I Project | Integrated Rural Development',
            'seo_description' => 'Read about IRDP I, the SIF Ghana rural development programme that created employment opportunities and delivered infrastructure across districts.',
        ],
        'uprp' => [
            'name' => 'UPRP',
            'full_name' => 'Urban Poverty Reduction Project',
            'status' => 'Completed',
            'timeline' => 'Completed',
            'funder' => 'Development Partners and Government of Ghana',
            'fund_amount' => '-',
            'zone' => 'Eastern Seaboard',
            'regions' => ['Greater Accra', 'Urban centres nationwide'],
            'image' => 'https://sifinghana.org/backend/images/uploads/_ENN6076.jpg1738337029.jpg',
            'summary' => "Targeted infrastructure and services delivered to Ghana's most deprived urban neighbourhoods, laying the template for SIF's urban work today.",
            'objectives' => [
                'Deliver targeted infrastructure to deprived urban neighbourhoods.',
                'Improve access to basic services in low-income urban communities.',
                'Establish an urban delivery template for future SIF programmes.',
            ],
            'outcomes' => [
                "Programme completed; informed SIF's current urban-facing project design.",
            ],
            'beneficiaries' => 'Residents of deprived urban neighbourhoods nationwide.',
            'seo_title' => 'UPRP Project | Urban Poverty Reduction',
            'seo_description' => 'Learn about UPRP, SIF Ghana’s urban poverty reduction programme delivering infrastructure and services to deprived urban communities.',
        ],
        'gprp' => [
            'name' => 'GPRP I and II',
            'full_name' => 'Ghana Poverty Reduction Project, Phases I and II',
            'status' => 'Completed',
            'timeline' => 'Completed',
            'funder' => 'AfDB and OFID',
            'fund_amount' => '-',
            'zone' => 'Eastern Seaboard',
            'regions' => ['Nationwide'],
            'image' => 'https://sifinghana.org/backend/images/uploads/badea%207.jpg1739437245.jpg',
            'summary' => "The programme that built SIF's foundation: two phases of poverty-reduction infrastructure delivered nationwide since incorporation in 1998.",
            'objectives' => [
                'Deliver foundational poverty-reduction infrastructure nationwide.',
                "Establish SIF's earliest partnerships with AfDB and OFID.",
            ],
            'outcomes' => [
                'Phase I delivered with AfDB financing; Phase II delivered with OFID financing.',
                'Foundational programme for all SIF work that followed.',
            ],
            'beneficiaries' => "Communities nationwide, since SIF's incorporation in 1998.",
            'seo_title' => 'GPRP I and II | Ghana Poverty Reduction Project',
            'seo_description' => 'Explore GPRP I and II, the poverty-reduction programme phases that helped establish SIF Ghana’s nationwide development delivery model.',
        ],
    ],
];
